/usr/bin/python3: can't open file '/home/neeraj/test/test_urls.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/neeraj/test/test_urls.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/neeraj/test/test_urls.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/neeraj/test/test_urls.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/neeraj/test/test_urls.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/home/neeraj/test/test_urls.py': [Errno 2] No such file or directory
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.002s

FAILED (errors=1)
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: setUpClass (__main__.TestCustomURLs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/test/test_urls.py", line 12, in setUpClass
    with open("urls.yaml", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'urls.yaml'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
